@echo off
echo Starting Full-Stack App in Development Mode...

echo Starting Backend...
start cmd /k "cd backend && set FLASK_APP=wsgi.py && set FLASK_ENV=development && set FLASK_DEBUG=1 && python -m flask run --port 5000"

echo Starting Frontend...
start cmd /k "cd frontend && npm run dev"
