""" Add plant fields and added_by audit to Assets

Revision ID: 4cd3e8cd95f6
Revises: 9033448e4baa
Create Date: 2026-09-12 18:12:40.313469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cd3e8cd95f6'
down_revision = '9033448e4baa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plant_name', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('string_group', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('commissioned_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('added_by_user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('added_by_email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('added_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'Users', ['added_by_user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Assets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('added_at')
        batch_op.drop_column('added_by_email')
        batch_op.drop_column('added_by_user_id')
        batch_op.drop_column('commissioned_date')
        batch_op.drop_column('string_group')
        batch_op.drop_column('plant_name')

    # ### end Alembic commands ###
