"""empty message

Revision ID: 9033448e4baa
Revises: 8c4aeb6ee8a2
Create Date: 2026-09-12 15:30:17.448762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9033448e4baa'
down_revision = '8c4aeb6ee8a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Prediction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('predicted_power_kw', sa.Float(), nullable=False),
    sa.Column('predicted_anomaly_score', sa.Float(), nullable=True),
    sa.Column('predicted_energy_loss', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['Assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('WeatherForecast',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('solar_radiation', sa.Float(), nullable=False),
    sa.Column('wind_speed', sa.Float(), nullable=False),
    sa.Column('precipitation', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['Assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('rated_power_kw', sa.Float(), nullable=True))
        batch_op.drop_column('rated_power')

    with op.batch_alter_table('SensorReadings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('power_output_kw', sa.Float(), nullable=True))
        batch_op.drop_column('power_output')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('SensorReadings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('power_output', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.drop_column('power_output_kw')

    with op.batch_alter_table('Assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rated_power', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.drop_column('rated_power_kw')
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')

    op.drop_table('WeatherForecast')
    op.drop_table('Prediction')
    # ### end Alembic commands ###
